[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solprofile = "EfwU21VVpG9aHLmYAM2zcEaPEDSRfXxCGv3S95zTNp8h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -- --nocapture"
