[package]
name = "solprofile-example"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "create"
path = "src/create.rs"

[[bin]]
name = "get"
path = "src/get.rs"

[[bin]]
name = "update"
path = "src/update.rs"

[dependencies]
anchor-lang = "0.30.1"
anchor-client = "0.30.1"
shellexpand = "3.1.0"
